- name: Ensure vim is installed
  homebrew:
    name: vim
    state: latest

- name: create required .vim and vim-plug directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ ansible_user_dir }}/.vim"
    - "{{ ansible_user_dir }}/.vim/autoload"
    - "{{ ansible_user_dir }}/.vim/plugged"

- name: install vim-plug vim plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_user_dir }}/.vim/autoload/plug.vim"
    mode: '0640'

- name: copy .vimrc
  template:
    src: vimrc.j2
    dest: "{{ ansible_user_dir }}/.vimrc"
    mode: '0640'
    backup: yes

- name: copy .ctrlpignore
  template:
    src: ctrlpignore.j2
    dest: "{{ ansible_user_dir }}/.ctrlpignore"
    mode: '0640'
    backup: yes
